### ISSUE TITLE
Screen captured by shutterbug is not correct

### ISSUE THREAD

**Issue by vishruth143** [assertthat/selenium-shutterbug#12] opened 2016-10-12 08:00 UTC
Hi @glib-briia,

My apologies for raising this bug again and again.
I have written the below code. But the output screen captured by shutter bug is not correct. I double checked all my xpaths and its correctly recognizing the web elements. Am I doing something wrong here.

```
import java.awt.Color;
import java.awt.Font;
import java.util.Date;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import com.assertthat.selenium_shutterbug.core.Shutterbug;

public class ShutterBug {

    public static void main(String[] args) {
//      System.setProperty("webdriver.chrome.driver", "C:\\Eclipse\\Drivers\\chromedriver.exe");
//      WebDriver driver = new ChromeDriver();
        System.setProperty("webdriver.gecko.driver","C:\\Eclipse\\Drivers\\geckodriver.exe");
        WebDriver driver = new FirefoxDriver();
        driver.manage().window().maximize();
        driver.get("https://www.google.com/");
        WebElement googleLogo = driver.findElement(By.xpath(".//*[@id='hplogo']"));
        WebElement searchBtn = driver.findElement(By.xpath(".//*[@id='tsf']/div[2]/div[3]/center/input[1]"));
        WebElement searchBox = driver.findElement(By.xpath(".//*[@id='lst-ib']"));

        //searchBox.sendKeys("Testing");    

        Shutterbug.shootPage(driver)
            .blur(searchBox)
            .highlight(searchBtn)
            .monochrome(googleLogo)
            .highlightWithText(googleLogo, Color.blue, 3, "Monochromed logo",Color.blue, new Font("SansSerif", Font.BOLD, 20))
            .highlightWithText(searchBox, "Blurred secret words")
            .withTitle("Google home page - " + new Date())
            .withName("home_page")
            .withThumbnail(0.7)
            .save("C:\\Users\\Vishvambruth JT\\Desktop\\Screen.jpg");
            driver.quit();      
    }
}
```

**I'm Using:**
**Firefox Version:** 49.0.1
**Chrome Version:** 54.0.2840.59 m
**Selenium Version:** Version 3.0.0
**OS:** Win10 64 bit
**Java:** 1.8

**Output Screen captured by shutterbug**

![home_page](https://cloud.githubusercontent.com/assets/21016972/19301956/c397933a-9027-11e6-9d3b-41270d5015bb.png)

**Comment by glib-briia** [comment] 2016-10-14 11:01
Hi @vishruth143 ,

I cant reproduce the issue you are having. Tried executing your code with the same set up.
Works as expected.

![home_page](https://cloud.githubusercontent.com/assets/16775850/19385330/daecb698-9205-11e6-9baf-9127fd7d9e86.png)

Are you still seeing this issue?

**Comment by vishruth143** [comment] 2016-10-15 09:54
Hi @glib-briia,

Something is wrong. I'm still not able to capture the right screen shot. I checked my browser zoom level also its at 100%. 

**When I run the above code using the Mozilla browser I get the below error.**
```
Oct 15, 2016 4:50:42 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
1476525043282	Marionette	INFO	Listening on port 57595
1476525044735	Marionette	INFO	startBrowser 643d0e05-c3fb-4eec-9d6c-1728b59345d1
Oct 15, 2016 4:50:45 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Exception in thread "main" java.lang.NullPointerException
	at org.openqa.selenium.remote.RemoteWebElement.getLocation(RemoteWebElement.java:338)
	at com.assertthat.selenium_shutterbug.utils.web.Coordinates.<init>(Coordinates.java:23)
	at com.assertthat.selenium_shutterbug.core.PageSnapshot.blur(PageSnapshot.java:120)
	at ShutterBug.main(ShutterBug.java:29)
```
**But when I run the same code using the chrome browser I get the below screenshot.**

![home_page](https://cloud.githubusercontent.com/assets/21016972/19409132/64150e1a-9293-11e6-80bf-d47f6957a575.png)

**Comment by vishruth143** [comment] 2016-10-15 18:45
Hi @glib-briia ,

With **Selenium 3.0.0** the issue with Mozilla Firefox browser got resolved now I'm able to get the correct screen shot as below.

![home_page](https://cloud.githubusercontent.com/assets/21016972/19412440/e7cf9bba-92db-11e6-9293-db145696a15f.png)

But when I run the same code in Chrome I still get incorrect screen shot as below.

![home_page](https://cloud.githubusercontent.com/assets/21016972/19412504/acf33afe-92dd-11e6-8e9c-86fe88bc9fe8.png)

**Comment by glib-briia** [comment] 2016-10-16 10:02
Hi @vishruth143,

Thank you for update! Which chromedriver version are you using?

**Comment by vishruth143** [comment] 2016-10-17 02:43
Hi @glib-briia,

I'm using chrome driver version 2.24.

**Comment by vishruth143** [comment] 2016-11-20 03:36
Hi @glib-briia ,

I tried this issue again with the below setup. Still I'm facing the same issue i.e.
When I run the above code with Mozilla I get correct screen shot. 
But when I I run the above code with Chrome I get in-correct screen shot. 
**I'm Using:**
**Firefox Version:** 50.0
**Chrome Version:** 54.0.2840.99 m
**ChromeDriver Version:** 2.25
**Selenium Version:** 3.0.1
**OS:** Win10 64 bit
**Java:** 1.8
**Mozilla Screenshot:**
![home_page](https://cloud.githubusercontent.com/assets/21016972/20460137/13a30d96-aea0-11e6-8210-fc4df100355c.png)

**Chrome Screenshot:**
![home_page](https://cloud.githubusercontent.com/assets/21016972/20460139/29c339de-aea0-11e6-8baa-8752d8310cd0.png)

**Comment by glib-briia** [comment] 2017-04-21 09:30
Unable to reproduce. Closing as wontfix

**Comment by dzaiats** [comment] 2017-12-04 14:58
Hi there! I'm a creator of [Automotion](https://github.com/ITArray/Automotion-Java) framework.
The problem described above is the scaling factor of the screen. Retina vs no retina.
We had the same in Automotion but it's fixed by introducing the manual configuration for the scaling factor.

**Comment by glib-briia** [comment] 2017-12-04 21:10
Thank you @dzaiats.

@vishruth143 , have you tried using the following:
```
Shutterbug.shootPage(driver, ScrollStrategy.BOTH_DIRECTIONS,500,true).save();
```
true in the arguments list stand for devicePixelRatio on retina displays.
Thanks,
Glib

**Comment by glib-briia** [comment] 2018-07-18 12:07
Closing due to inactivity

**Closed by glib-briia** 2018-07-18 12:07 UTC
Labels: awaiting answer
