### ISSUE TITLE
ScrollTo

### ISSUE THREAD

**Issue by noppakrit** [assertthat/selenium-shutterbug#6] opened 2016-10-07 03:18 UTC
I have a problem about scrolling (ScrollTo), it doesn't work.
The program capture the visible page.
Thx

**Comment by glib-briia** [comment] 2016-10-07 07:07
Could you provide example of usage and steps to reproduce?

**Comment by noppakrit** [comment] 2016-10-07 08:33
My Code
Shutterbug.shootPage(driver,ScrollStrategy.BOTH_DIRECTIONS).save();

Expected result: 01.png 
![01](https://cloud.githubusercontent.com/assets/1941483/19183550/160a45c8-8ca3-11e6-96e6-39e86ad161a1.png)

Actual result: 02.png
![02](https://cloud.githubusercontent.com/assets/1941483/19183574/2fcf5430-8ca3-11e6-9f0f-5d0ea26750ea.png)

**Comment by glib-briia** [comment] 2016-10-07 08:38
Thank you, could you please let me know the browser you are using and shutterbug version

**Comment by noppakrit** [comment] 2016-10-07 08:40
Chrome
![image](https://cloud.githubusercontent.com/assets/1941483/19183827/5c6fcf32-8ca4-11e6-86b9-70dacffd4445.png)

**Comment by noppakrit** [comment] 2016-10-07 08:41
Vesion of selenium-shutterbug is 0.3

**Comment by glib-briia** [comment] 2016-10-07 08:42
Thank you.
Did you have the same issue with shutterbug version 0.2?

**Comment by noppakrit** [comment] 2016-10-07 08:57
V 0.2 is same result
![2016_10_07_15_53_49_754](https://cloud.githubusercontent.com/assets/1941483/19184233/5eed8afe-8ca6-11e6-9f70-e4f5e75ef035.png)

I revise the js from scrollTo --> scrollBy 
the system could scroll the page but fail to merge image
![2016_10_07_10_04_39_005](https://cloud.githubusercontent.com/assets/1941483/19184319/ba30730e-8ca6-11e6-8223-ab1a424c365d.png)

**Comment by glib-briia** [comment] 2016-10-09 16:12
Hi @noppakrit,

Are you getting any exceptions in the console?

The reason the page fails to scroll could be that some other JS is executed on the page while you are trying to make the screenshot. You could try to wait for [the page to fully load ](https://www.assertthat.com/posts/selenium_waiting_for_page_to_load_in_ajax_rich_applications) before making your screenshot.

**Comment by noppakrit** [comment] 2016-10-10 02:03
My Code
try {
            Thread.sleep(30000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Shutterbug.shootPage(driver,ScrollStrategy.BOTH_DIRECTIONS.BOTH_DIRECTIONS).save("D:\\1234");

![2016_10_10_08_58_32_508](https://cloud.githubusercontent.com/assets/1941483/19225510/1d54ad10-8ec8-11e6-9b7d-e83200831338.png)

Console Log
[log.txt](https://github.com/assertthat/selenium-shutterbug/files/518703/log.txt)

**Comment by glib-briia** [comment] 2016-10-11 08:38
Hi @noppakrit ,

Are you having the issue only on [this](https://cloud.githubusercontent.com/assets/1941483/19225510/1d54ad10-8ec8-11e6-9b7d-e83200831338.png) page or it fails to scroll everywhere in your application?

Its hard to say what is going wrong based on information provided.

**Comment by noppakrit** [comment] 2016-10-11 16:45
[Tue Oct 11 2016 23:36:09 GMT+0700 (SE Asia Standard Time)] Initialize JQuery...
Initialize JQuery...Window Events
Initialize JQuery...Decorator Layout
configDecorator
floatTheadSetup/rec2: 6.565ms
floatTheadSetup: 8.405ms
Initialize JQuery...View Control
Initialize JQuery...Page Control
Initialize JQuery...Input Control
Initialize JQuery...Input/Record
setupInputRecordKey: 0.096ms
configInputRecord: 0.820ms
setupFilterListRecord BEGIN
setupFilterListRecord END
setupInputGlobalSearch2014R3
[Tue Oct 11 2016 23:36:09 GMT+0700 (SE Asia Standard Time)] dataChanged_setup BEGIN
[Tue Oct 11 2016 23:36:09 GMT+0700 (SE Asia Standard Time)] dataChanged_setup Control Input Count is 0
[Tue Oct 11 2016 23:36:09 GMT+0700 (SE Asia Standard Time)] dataChanged_setup END
Initialize JQuery... Common Config DONE
Initialize JQuery... Initialize script for current page (pageReady)
[Tue Oct 11 2016 23:36:09 GMT+0700 (SE Asia Standard Time)] pageReady...
INIT>loadMyTeam:/****/custom-2014R3/raw/UStyle.do?rec=AM_Team14&uAction=init&noframe=1&cachetime=1476203769654
INIT>loadMyTeam:/****/custom-2014R3/raw/UStyle.do?rec=AM_Benefit15&srcTitle=Benefit&showLines=3&uAction=init&noframe=1&cachetime=1476203769655
[Tue Oct 11 2016 23:36:09 GMT+0700 (SE Asia Standard Time)] pageReady... DONE
Page Ready: 12.389ms
[Tue Oct 11 2016 23:36:09 GMT+0700 (SE Asia Standard Time)] Initialize JQuery... DONE
Document Ready: 71.715ms
Refused to display 'https://www.****.net/****-central/loginRedirectSuccess.jsp' in a frame because it set 'X-Frame-Options' to 'DENY'.
XHR finished loading: GET "https://****.****.net/****/ajax/profile/user-info".
XHR finished loading: GET "https://****.****.net/****/ajax/profile/user-menu".
XHR finished loading: GET "https://****.****.net/****/ajax/utalk/utalk-list".
XHR finished loading: GET "https://****.****.net/****/custom-2014R3/raw/UStyle.do?loadOnly=true&uAction=init&rec=AM_Anal14&noframe=&ajax=1&raw=1&_=1476203769657".
Object {readyState: 4, responseText: "
↵
↵
↵
↵", status: 200, statusText: "OK"}
XHR finished loading: GET "https://****.****.net/****/custom-2014R3/raw/UStyle.do?rec=AM_Team14&uAction=init&noframe=1&cachetime=1476203769654".
XHR finished loading: GET "https://****.****.net/****/custom-2014R3/raw/UStyle.do?rec=AM_Benefit15&srcTitle=Benefit&showLines=3&uAction=init&noframe=1&cachetime=1476203769655".
XHR finished loading: GET "https://****.****.net/****/ajax/profile/user-allmenus".
[receiveAllLeftMenus] Loading AllMenus DONE. len=492
[Tue Oct 11 2016 23:36:10 GMT+0700 (SE Asia Standard Time)] Initialize JQuery...
Initialize JQuery...Window Events
Initialize JQuery...Decorator Layout
configDecorator
floatTheadSetup/rec2: 4.849ms
floatTheadSetup: 8.043ms
Initialize JQuery...View Control
Initialize JQuery...Page Control
Initialize JQuery...Input Control
Initialize JQuery...Input/Record
setupInputRecordKey: 0.101ms
configInputRecord: 0.914ms
setupFilterListRecord BEGIN
setupFilterListRecord END
[Tue Oct 11 2016 23:36:10 GMT+0700 (SE Asia Standard Time)] dataChanged_setup BEGIN
[Tue Oct 11 2016 23:36:10 GMT+0700 (SE Asia Standard Time)] dataChanged_setup Control Input Count is 0
[Tue Oct 11 2016 23:36:10 GMT+0700 (SE Asia Standard Time)] dataChanged_setup END
Initialize JQuery... Common Config DONE
Initialize JQuery... Initialize script for current page (pageReady)
[Tue Oct 11 2016 23:36:10 GMT+0700 (SE Asia Standard Time)] pageReady...
Calendar14 Init BEGIN
[Tue Oct 11 2016 23:36:10 GMT+0700 (SE Asia Standard Time)] pageReady... DONE
Page Ready: 12.424ms
[Tue Oct 11 2016 23:36:10 GMT+0700 (SE Asia Standard Time)] Initialize JQuery... DONE
Document Ready: 51.471ms
Running Ginger Widget  version 0.1.0.608
Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required
Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required
scrollTo(0,200) <--- Not work
undefined
scrollBy(0,200) <--- work
undefined

**Comment by glib-briia** [comment] 2016-10-11 21:43
Have you tried just in Chrome? Could you try same in FF and IE

**Comment by noppakrit** [comment] 2016-10-12 02:12
FF

[Wed Oct 12 2016 09:08:25 GMT+0700 (SE Asia Standard Time)] Initialize JQuery...
js-2015...=2.9.12 (line 13)
Initialize JQuery...Window Events
js-2015...=2.9.12 (line 13)
Initialize JQuery...Decorator Layout
js-2015...=2.9.12 (line 13)
configDecorator
-...=2.9.12 (line 10)
GET https://tuf..net//ajax/profile/user-info
	
304 Not Modified
		212ms	
js-2015...=2.9.12 (line 2)
GET https://tuf..net//ajax/profile/user-menu
	
304 Not Modified
		212ms	
js-2015...=2.9.12 (line 2)
GET https://tuf..net//ajax/utalk/utalk-list
	
200 OK
		156ms	
js-2015...=2.9.12 (line 2)
GET https://tuf..net//ajax/profile/user-allmenus
	
304 Not Modified
		217ms	
js-2015...=2.9.12 (line 2)
floatTheadSetup/rec2: 1.11ms
-...=2.9.12 (line 1264)
floatTheadSetup: 5.18ms
-...=2.9.12 (line 1299)
Initialize JQuery...View Control
js-2015...=2.9.12 (line 13)
Initialize JQuery...Page Control
js-2015...=2.9.12 (line 13)
Initialize JQuery...Input Control
js-2015...=2.9.12 (line 13)
Initialize JQuery...Input/Record
js-2015...=2.9.12 (line 13)
9:8:25.772 configInputRecord
9:8:25.774 setupInputRecordKey
setupInputRecordKey: 1.37ms
js-2015...=2.9.12 (line 144)
configInputRecord: 2.86ms
js-2015...=2.9.12 (line 126)
setupFilterListRecord BEGIN
js-2015...=2.9.12 (line 189)
setupFilterListRecord END
js-2015...=2.9.12 (line 196)
setupInputGlobalSearch2014R3
-...=2.9.12 (line 616)
[Wed Oct 12 2016 09:08:25 GMT+0700 (SE Asia Standard Time)] dataChanged_setup BEGIN
js-2015...=2.9.12 (line 2)
[Wed Oct 12 2016 09:08:25 GMT+0700 (SE Asia Standard Time)] dataChanged_setup Control Input Count is 0
js-2015...=2.9.12 (line 2)
[Wed Oct 12 2016 09:08:25 GMT+0700 (SE Asia Standard Time)] dataChanged_setup END
js-2015...=2.9.12 (line 2)
Initialize JQuery... Common Config DONE
js-2015...=2.9.12 (line 13)
9:8:25.798 Show cmdline
Initialize JQuery... Initialize script for current page (pageReady)
js-2015...=2.9.12 (line 13)
[Wed Oct 12 2016 09:08:25 GMT+0700 (SE Asia Standard Time)] pageReady...
js-2015...=2.9.12 (line 13)
INIT>loadMyTeam://custom-2014R3/raw/UStyle.do?rec=AM_Team14&uAction=init&noframe=1&cachetime=1476238105802
UStyle....on=init (line 460)
GET https://tuf..net//custom-2014R3/raw/U...4&uAction=init&noframe=1&cachetime=1476238105802
	
200 OK
		180ms	
js-2015...=2.9.12 (line 2)
GET https://tuf..net//custom-2014R3/raw/U...=AM_Anal14&noframe=&ajax=1&raw=1&_=1476238105809
	
200 OK
		199ms	
js-2015...=2.9.12 (line 2)
[Wed Oct 12 2016 09:08:25 GMT+0700 (SE Asia Standard Time)] pageReady... DONE
js-2015...=2.9.12 (line 13)
Page Ready: 20.80ms
js-2015...=2.9.12 (line 25)
[Wed Oct 12 2016 09:08:25 GMT+0700 (SE Asia Standard Time)] Initialize JQuery... DONE
js-2015...=2.9.12 (line 13)
Document Ready: 130.05ms
js-2015...=2.9.12 (line 24)
[Wed Oct 12 2016 09:08:26 GMT+0700 (SE Asia Standard Time)] Initialize JQuery...
js-2015...=2.9.12 (line 13)
Initialize JQuery...Window Events
js-2015...=2.9.12 (line 13)
Initialize JQuery...Decorator Layout
js-2015...=2.9.12 (line 13)
configDecorator
-...=2.9.12 (line 10)
floatTheadSetup/rec2: 1.61ms
-...=2.9.12 (line 1264)
floatTheadSetup: 7.63ms
-...=2.9.12 (line 1299)
Initialize JQuery...View Control
js-2015...=2.9.12 (line 13)
Initialize JQuery...Page Control
js-2015...=2.9.12 (line 13)
Initialize JQuery...Input Control
js-2015...=2.9.12 (line 13)
Initialize JQuery...Input/Record
js-2015...=2.9.12 (line 13)
9:8:26.221 configInputRecord
9:8:26.223 setupInputRecordKey
setupInputRecordKey: 1.96ms
js-2015...=2.9.12 (line 144)
configInputRecord: 3.79ms
js-2015...=2.9.12 (line 126)
setupFilterListRecord BEGIN
js-2015...=2.9.12 (line 189)
setupFilterListRecord END
js-2015...=2.9.12 (line 196)
[Wed Oct 12 2016 09:08:26 GMT+0700 (SE Asia Standard Time)] dataChanged_setup BEGIN
js-2015...=2.9.12 (line 2)
[Wed Oct 12 2016 09:08:26 GMT+0700 (SE Asia Standard Time)] dataChanged_setup Control Input Count is 0
js-2015...=2.9.12 (line 2)
[Wed Oct 12 2016 09:08:26 GMT+0700 (SE Asia Standard Time)] dataChanged_setup END
js-2015...=2.9.12 (line 2)
Initialize JQuery... Common Config DONE
js-2015...=2.9.12 (line 13)
9:8:26.236 Show cmdline
Initialize JQuery... Initialize script for current page (pageReady)
js-2015...=2.9.12 (line 13)
[Wed Oct 12 2016 09:08:26 GMT+0700 (SE Asia Standard Time)] pageReady...
js-2015...=2.9.12 (line 13)
Calendar14 Init BEGIN
UStyle....&locId= (line 1049)
[Wed Oct 12 2016 09:08:26 GMT+0700 (SE Asia Standard Time)] pageReady... DONE
js-2015...=2.9.12 (line 13)
Page Ready: 16.91ms
js-2015...=2.9.12 (line 25)
[Wed Oct 12 2016 09:08:26 GMT+0700 (SE Asia Standard Time)] Initialize JQuery... DONE
js-2015...=2.9.12 (line 13)
Document Ready: 80.66ms
js-2015...=2.9.12 (line 24)
Object { readyState=4,  responseText="\r\n\r\n\r\n\r\n",  status=200,  more...}
UStyle....on=init (line 446)
[receiveAllLeftMenus] Loading AllMenus DONE. len=635
-...=2.9.12 (line 963)
Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
util.js (line 208)
Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required
util.js (line 208)
Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
util.js (line 208)
Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required
util.js (line 208)
scrollTo(0,200) <-- Not work
undefined
scrollBy(0,200) <-- Work
undefined
4
[DEBUG] this.offsetWidth=220, this.scrollWidth=220
-...=2.9.12 (line 334)
No activity to profile

**Comment by noppakrit** [comment] 2016-10-12 02:15
IE

HTML1300: Navigation occurred.
UStyle.do
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
UStyle.do
[Wed Oct 12 2016 09:13:17 GMT+0700 (SE Asia Standard Time)] Initialize JQuery...
Initialize JQuery...Window Events
Initialize JQuery...Decorator Layout
configDecorator
floatTheadSetup/rec2: 0.482ms
floatTheadSetup: 1.874ms
Initialize JQuery...View Control
Initialize JQuery...Page Control
Initialize JQuery...Input Control
Initialize JQuery...Input/Record
configInputRecord: 884.91ms
setupInputRecordKey: 885.323ms
setupInputRecordKey: 0.367ms
configInputRecord: 0.63ms
setupFilterListRecord BEGIN
setupFilterListRecord END
setupInputGlobalSearch2014R3
[Wed Oct 12 2016 09:13:18 GMT+0700 (SE Asia Standard Time)] dataChanged_setup BEGIN
[Wed Oct 12 2016 09:13:18 GMT+0700 (SE Asia Standard Time)] dataChanged_setup Control Input Count is 0
[Wed Oct 12 2016 09:13:18 GMT+0700 (SE Asia Standard Time)] dataChanged_setup END
Initialize JQuery... Common Config DONE
Show cmdline: 895.376ms
Initialize JQuery... Initialize script for current page (pageReady)
[Wed Oct 12 2016 09:13:18 GMT+0700 (SE Asia Standard Time)] pageReady...
INIT>loadMyTeam://custom-2014R3/raw/UStyle.do?rec=AM_Team14&uAction=init&noframe=1&cachetime=1476238398018
INIT>loadMyTeam://custom-2014R3/raw/UStyle.do?rec=AM_Benefit15&srcTitle=Benefit&showLines=3&uAction=init&noframe=1&cachetime=1476238398020
[Wed Oct 12 2016 09:13:18 GMT+0700 (SE Asia Standard Time)] pageReady... DONE
Page Ready: 16.901ms
[Wed Oct 12 2016 09:13:18 GMT+0700 (SE Asia Standard Time)] Initialize JQuery... DONE
Document Ready: 93.513ms
[object Object]
   {
      [functions]: ,
      __proto__: { },
      readyState: 4,
      responseText: "



",
      status: 200,
      statusText: "OK"
   }

[receiveAllLeftMenus] Loading AllMenus DONE. len=492
[Wed Oct 12 2016 09:13:18 GMT+0700 (SE Asia Standard Time)] Initialize JQuery...
Initialize JQuery...Window Events
Initialize JQuery...Decorator Layout
configDecorator
floatTheadSetup/rec2: 0.589ms
floatTheadSetup: 2.406ms
Initialize JQuery...View Control
Initialize JQuery...Page Control
Initialize JQuery...Input Control
Initialize JQuery...Input/Record
configInputRecord: 1,920.844ms
setupInputRecordKey: 1,921.198ms
setupInputRecordKey: 0.309ms
configInputRecord: 0.54ms
setupFilterListRecord BEGIN
setupFilterListRecord END
[Wed Oct 12 2016 09:13:19 GMT+0700 (SE Asia Standard Time)] dataChanged_setup BEGIN
[Wed Oct 12 2016 09:13:19 GMT+0700 (SE Asia Standard Time)] dataChanged_setup Control Input Count is 0
[Wed Oct 12 2016 09:13:19 GMT+0700 (SE Asia Standard Time)] dataChanged_setup END
Initialize JQuery... Common Config DONE
Show cmdline: 1,924.738ms
Initialize JQuery... Initialize script for current page (pageReady)
[Wed Oct 12 2016 09:13:19 GMT+0700 (SE Asia Standard Time)] pageReady...
Calendar14 Init BEGIN
[Wed Oct 12 2016 09:13:19 GMT+0700 (SE Asia Standard Time)] pageReady... DONE
Page Ready: 30.949ms
[Wed Oct 12 2016 09:13:19 GMT+0700 (SE Asia Standard Time)] Initialize JQuery... DONE
Document Ready: 97.807ms
Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required
Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required
scrollTo(0,200) <-- Not work
undefined
scrollBy(0,200) <-- Work
undefined

**Comment by glib-briia** [comment] 2017-04-21 09:29
Application specific behavior. Closing as wontfix

**Closed by glib-briia** 2017-04-21 09:29 UTC
Labels: wontfix
